services:
  postgres:
    image: postgres:16
    container_name: todos-postgres
    environment:
      POSTGRES_DB: todos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lahatranomena!!!
    ports:
      - "5433:5432"
    volumes:
      - todos_postgres_data:/var/lib/postgresql/data

volumes:
  todos_postgres_data: