spring.application.name=todos

spring.datasource.username=postgres
spring.datasource.password=lahatranomena!!!
spring.datasource.url=jdbc:postgresql://localhost:5435/todos

spring.flyway.enabled=true
spring.flyway.locations=classpath:migration
spring.jpa.open-in-view=false